//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aadhar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AadharDBEntities : DbContext
    {
        public AadharDBEntities()
            : base("name=AadharDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AadharMaster> AadharMasters { get; set; }
        public virtual DbSet<IntigrationMaster> IntigrationMasters { get; set; }
        public virtual DbSet<ConnectedAccountMaster> ConnectedAccountMasters { get; set; }
        public virtual DbSet<ContectMaster> ContectMasters { get; set; }
        public virtual DbSet<DigitalInfoMaster> DigitalInfoMasters { get; set; }
        public virtual DbSet<GardianMaster> GardianMasters { get; set; }
        public virtual DbSet<OTPMaster> OTPMasters { get; set; }
        public virtual DbSet<PermentAddressMaster> PermentAddressMasters { get; set; }
        public virtual DbSet<PersentAddressMaster> PersentAddressMasters { get; set; }
    }
}
