//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aadhar
{
    using System;
    using System.Collections.Generic;
    
    public partial class AadharMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AadharMaster()
        {
            this.ContectMasters = new HashSet<ContectMaster>();
            this.IntigrationMasters = new HashSet<IntigrationMaster>();
            this.PermentAddressMasters = new HashSet<PermentAddressMaster>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> aadharNo { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> bloodGroup { get; set; }
        public bool isGaurded { get; set; }
    
        public virtual ConnectedAccountMaster ConnectedAccountMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContectMaster> ContectMasters { get; set; }
        public virtual DigitalInfoMaster DigitalInfoMaster { get; set; }
        public virtual GardianMaster GardianMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntigrationMaster> IntigrationMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermentAddressMaster> PermentAddressMasters { get; set; }
        public virtual PersentAddressMaster PersentAddressMaster { get; set; }
    }
}
