//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aadhar
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContectMaster
    {
        public int id { get; set; }
        public Nullable<decimal> phoneNumber { get; set; }
        public string emailId { get; set; }
        public bool isPrimary { get; set; }
    
        public virtual AadharMaster AadharMaster { get; set; }
    }
}
