//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aadhar
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    
    [Serializable]
    [DataContract]
    public partial class IntigrationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IntigrationMaster()
        {
            this.OTPMasters = new HashSet<OTPMaster>();
        }

        [DataMember]
        public int requestId { get; set; }
        [DataMember]
        public int id { get; set; }
        [DataMember]
        public decimal aadharNo { get; set; }
        [DataMember]
        public string externalUniqueId { get; set; }
        [DataMember]
        public string clientType { get; set; }
        [DataMember]
        public Nullable<System.DateTime> requestDateTime { get; set; }
    
        public virtual AadharMaster AadharMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTPMaster> OTPMasters { get; set; }
    }
}
