//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aadhar
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTPMaster
    {
        public int requestId { get; set; }
        public decimal mOTP { get; set; }
        public decimal eOTP { get; set; }
        public int id { get; set; }
    
        public virtual IntigrationMaster IntigrationMaster { get; set; }
    }
}
