//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aadhar
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;

    [Serializable]
    [DataContract]
    public partial class OTPMaster
    {
        [DataMember]
        public int requestId { get; set; }
        [DataMember]
        public decimal mOTP { get; set; }
        [DataMember]
        public decimal eOTP { get; set; }
    
        public virtual IntigrationMaster IntigrationMaster { get; set; }
    }
}
