//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErtoOfGujarat
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class AppointmentDateMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppointmentDateMaster()
        {
            this.AppointmentTimeMasters = new HashSet<AppointmentTimeMaster>();
        }
    
        public int pKey { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> totalCount { get; set; }
        public Nullable<int> vanue { get; set; }
    
        public virtual vanueMaster vanueMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTimeMaster> AppointmentTimeMasters { get; set; }
    }
}
