//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErtoOfGujarat
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigitalInfoMaster
    {
        public int pkey { get; set; }
        public int id { get; set; }
        public byte[] photo { get; set; }
        public byte[] lThumb { get; set; }
        public byte[] rThumb { get; set; }
        public byte[] lFingers { get; set; }
        public byte[] rFingers { get; set; }
        public byte[] signature { get; set; }
    
        public virtual ErtoMaster ErtoMaster { get; set; }
    }
}
