//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErtoOfGujarat
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseMaster
    {
        public string licenseNo { get; set; }
        public int id { get; set; }
        public int licenseType { get; set; }
        public string validThrough { get; set; }
        public System.DateTime validFrom { get; set; }
        public System.DateTime validTill { get; set; }
    
        public virtual ErtoMaster ErtoMaster { get; set; }
    }
}
