//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErtoOfGujarat
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermentAddressMaster
    {
        public int pKey { get; set; }
        public int id { get; set; }
        public string mainAddress { get; set; }
        public string nearByAddress { get; set; }
        public string optionalAddress { get; set; }
        public string city { get; set; }
        public Nullable<decimal> pincode { get; set; }
        public bool IsLiveInPermentAddress { get; set; }
    
        public virtual ErtoMaster ErtoMaster { get; set; }
    }
}
