//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErtoOfGujarat
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponceMaster
    {
        public int pKey { get; set; }
        public decimal aadharNo { get; set; }
        public string uniqueId { get; set; }
        public Nullable<int> requestId { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<decimal> phoneNumber { get; set; }
        public string emailId { get; set; }
        public Nullable<decimal> mOTP { get; set; }
        public Nullable<decimal> eOTP { get; set; }
    }
}
