//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErtoOfGujarat
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerificationMaster
    {
        public int pkey { get; set; }
        public Nullable<int> verifyWhom { get; set; }
        public Nullable<int> verifyBy { get; set; }
        public Nullable<System.DateTime> verifiedAt { get; set; }
        public Nullable<bool> verified { get; set; }
    
        public virtual AuthorizePerson AuthorizePerson { get; set; }
        public virtual ErtoMaster ErtoMaster { get; set; }
    }
}
